on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: Duffney/setup-notation@v0.1.1
      # To use this repository's private action,
      # you must check out the repository
      - run: notation sign --help
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          image-name: 'notaryarc/webapp:v1'
          envolope-type: 'cose'
          media-type: 'floppy'